### ISSUE TITLE
Create Vm with UUID of previous vm

### ISSUE THREAD

**Issue by kevinmeziere** [project-fifo/r-vmadm#13]
Currently it is not possible to create a vm with a uuid of a previous vm because zfs snapshot already exists.

Jul 01 06:22:54.617 DEBG Creating ZFS snapshot, snapshot: zroot/jails/e022d0f8-5630-11e7-b660-9b2d243d4404@fe0b9b05-1f3e-4b11-b0ae-8494bb6ecd53, req_id: 73c1e9ad-fa4b-421a-99b8-1363f3370642
command failed: Failed create snapshot

zfs list -t snapshot
zroot/jails/e022d0f8-5630-11e7-b660-9b2d243d4404@final                                     0      -   355M  -
zroot/jails/e022d0f8-5630-11e7-b660-9b2d243d4404@fe0b9b05-1f3e-4b11-b0ae-8494bb6ecd53      0      -   355M  -

**Comment by Licenser** [comment]
hmm I can't reproduce this, could it be that it's a left over from some test that failed?
