### ISSUE TITLE
creating a new jail should put it into 'installed' state

### ISSUE THREAD

**Issue by Licenser** [project-fifo/r-vmadm#16]
When creating a jail it ends up in 'installing' not 'installed'.

**Comment by Licenser** [comment]
it now ends in installed

**Comment by kevinmeziere** [comment]
"installing" seems like the correct state. There will be some sort of script that needs to run to startup a zone, once that returns 0 or some particular file is touched then you can assume that the jail is "installed"

**Comment by Licenser** [comment]
Yes and no, right now there is no script so there technically isn't an installing state. It's either there or not. Putting installing there at this point is more confusing than helpful, but it's easy to change once we know more of what we need to run :)

**Comment by Licenser** [comment]
I'm not even sure we need the state in the index at all since jails are quite different from zones. It might work best to do something like:

* has a ide => running
* has an 'installed' file in the zone (aka init process was run) => installed
* otherwise => installing.

we got to see
