### ISSUE TITLE
devfs_ruleset shoudl be configurable

### ISSUE THREAD

**Issue by kevinmeziere** [project-fifo/r-vmadm#17]
devfs_ruleset referes to a rule in the file /etc/defaults/devfs.rules. While ruleset 4 works it is only a sample default shipped with freebsd. More sophisticated users than us will likely have their own ruleset so we should allow them to set it. A system wide config would be better than a default, a per vm setting would be better, especially if we want to grant certain vms more rights for example a particular device (gpu) in the future.

**Comment by Licenser** [comment]
not sure we can do per vm settings but yea a configurable system wide rule would make sense.
