### ISSUE TITLE
vmadm should not depend on /etc/jails

### ISSUE THREAD

**Issue by bartekrutkowski** [project-fifo/r-vmadm#40]
In FreeBSD the `/etc` directory is reserved for OS (so called 'base') config files and services. Instead of creating `/etc/jails/` vmadm should be using `/usr/local/etc/jails` or, better yet, something like `/usr/local/etc/vmadm` since 'jail' is a common name of FreeBSD technology and there are other jail managers that may clash or want to claim such path in future.

**Comment by Licenser** [comment]
Thanks for the input! That's good to know early on so the imact of changing it is minimal!
