### ISSUE TITLE
brand property

### ISSUE THREAD

**Issue by cneira** [project-fifo/r-vmadm#44]
@Licenser 
I think the brand value for a FreeBSD jail should be the OS name and for hardware virtualized jails the name of the hypervisor, so you could list them by brand. Just a suggestion 
```bash
root@fbsdvm:/usr/home/cnb # vmadm get fe0b9b05-1f3e-4b11-b0ae-8494bb6ecd53
```
```json
{
  "brand": "jail",
  "uuid": "fe0b9b05-1f3e-4b11-b0ae-8494bb6ecd53",
  "image_uuid": "616d4ab2-832c-11e7-9392-784f438c8d54",
  "alias": "test",
  "hostname": "test",
  "autoboot": false,
  "max_physical_memory": 1024,
  "cpu_cap": 100,
  "quota": 100,
  "max_shm_memory": 1024,
  "max_locked_memory": 1024,
  "nics": [
    {
      "interface": "net0",
      "mac": "02:5c:60:f7:72:cd",
      "nic_tag": "admin",
      "ip": "192.168.1.234",
      "netmask": "255.255.255.0",
      "gateway": "192.168.1.1",
      "primary": true
    }
  ],
  "max_lwps": 2000,
  "dns_domain": "local"
}
```

**Comment by Licenser** [comment]
The brand name has a meaning this is to be compatible w/ the SmartOS vmadm:

```
       brand:

           This will be one of 'joyent', 'joyent-minimal' or 'sngl' for OS
           virtualization and 'kvm' for full hardware virtualization. This is a
           required value for VM creation.

           type: string (joyent|joyent-minimal|kvm|sngl)
           vmtype: OS,KVM
           listable: yes
           create: yes
           update: no
```
Historrically it comes from the fact that zones in solaris could be 'branded' as in a Solaris 9 branded zone, a Solaris 10 branded zone, or even have custom brands (like `joyent`, `joyent-minimal` or `sngl`)

Effectively it's a mapping of 'what kind of container is this'.

* Joyent => classing SmartOS VM
* kvm => SmartOS KVM
* jail => FreeBSD jail
* bhyve => FreeBSD bhyve (perhaps one day ;))

**Comment by Licenser** [comment]
I might not understand correctly get what you mean, do you mean naming it `freebsd` instead of `jail`?

**Comment by Licenser** [comment]
The main issue with changing it would be that it's already encoded as `freebsd` in many places in fifo and I'd be very hesitant to break compatibility even if it was only in a dev build (I'm quite strict about backward compatibility ;) and I'm not sure the advantage of having it named `freebsd` instead of `jail` would justify the work of changing things around in a graceful manner.

**Comment by cneira** [comment]
My mistake, you are correct, I have should look at SmartOS vmadm man page first. What will be the vmtype of a jail that is running linux, it will be  lx like smartos. it should be lx right ?

PROPERTIES


       Every VM has a number of properties. The properties for a VM can be listed
       with the 'vmadm get <uuid>' command. Some of these properties can be
       included in a create payload, some can be included in the output or be used
       to sort output for the 'vmadm list' command. Not all fields will be
       included for all VMs. Below the fields are marked as:

           type -- type of the properties value.

           vmtype -- types of VM (KVM, LX, OS) for which this property applies.

**Comment by Licenser** [comment]
The `vmtype` in that snippet refers to how the man page describes properties (look at the earlier snippet it reads `vmtype: OS,KVM` to denote it's for OS zones and KVM vm's.

I must admit not sure how BSD jails work with Linux so I might say something wrong, but it'd probably be still a jail perhaps marked as `lx-jail` (it's `lx` for lx-zones). But I'm totally open to better suggestions, `lx-jail` just seems the most straight forward one.

For FiFo it'll be a subtype, like a lx-zone for fifo has the `type=zone` and the `zonetype=lx` it would be `type=jail` and `zonetype=lx` in the case of lx-jails (please ignore that it's named zonetype it's internal and has no effect ;))
